version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 1
    directory: "/"
    reviewers:
      - chronark
  - package-ecosystem: "npm"
    open-pull-requests-limit: 1
    directory: "/packages/*"
    reviewers:
      - chronark
