services:
  - type: web
    name: webapp
    env: node
    plan: starter
    buildCommand: |
      yarn  &&
      blitz build &&
      blitz prisma migrate deploy
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: perfolio-db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true

databases:
  - name: perfolio-db
    plan: starter
