name: Cypress

on: ["deployment_status"]

jobs:
  e2e:
    name: Integration tests
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: true

      - run: echo ${{toJson(github.event)}}
      - name: Integration test
        run: pnpm nx e2e app-e2e --record --key ${{secrets.CYPRESS_APP_RECORD_KEY}}
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
