name: Lighthouse

on: ["deployment_status"]
jobs:
  landing:
    runs-on: ubuntu-latest
    if: ${{ github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Preview – landing-perfolio' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: run lhci
        run: |
          npx @lhci/cli autorun --config=./apps/landing/lighthouserc.js \
          --collect.url=${{ github.event.deployment_status.target_url }} \
          --collect.url=${{ github.event.deployment_status.target_url }}/imprint \
          --collect.url=${{ github.event.deployment_status.target_url }}/privacy
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          NEXT_PUBLIC_CLERK_FRONTEND_API: ${{ secrets.NEXT_PUBLIC_CLERK_FRONTEND_API }}

  app:
    runs-on: ubuntu-latest
    if: ${{ github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Preview - app-perfolio' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: run lhci
        run: |
          npx @lhci/cli autorun --config=./apps/app/lighthouserc.js \
          --collect.url=${{ github.event.deployment_status.target_url }}/subscribe
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          NEXT_PUBLIC_CLERK_FRONTEND_API: ${{ secrets.NEXT_PUBLIC_CLERK_FRONTEND_API }}
